# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: JDB-SERVER

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]

stages:
  - stage: 'Deploy_production'
    condition: eq(variables['branchName'], 'master')
    jobs:
      - job: 'Production'
        displayName: 'Build artifacts'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '20.12.2'
          displayName: 'Install Node.js'
        - script: |
            npm install
          displayName: 'npm install'
        - script: |
            npm i -g @angular/cli@17.3.6
          displayName: 'Instal Angular CLI'
        - script: |
            ng build --configuration production
          displayName: 'NG build'
        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: 'dist/**'
            targetFolder: $(Build.ArtifactStagingDirectory)
          displayName: 'Copy npm package'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'cuentas-front-production'
            publishLocation: 'Container'
